apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: demo-py-web-app
  name: demo-py-web-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-py-web-app
  template:
    metadata:
      labels:
        app: demo-py-web-app
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - image: demo-py-web-app:v1
        name: demo-py-web-app
        ports:
        - containerPort: 5000
        resources:
          requests:
            cpu: 50m
            memory: 128Mi
          limits:
            cpu: 100m
            memory: 256Mi
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 15
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 20
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: demo-py-web-app
  labels:
    app: demo-py-web-app
spec:
  ports:
  - port: 80
    protocol: TCP
    name: http
    targetPort: 5000
  selector:
    app: demo-py-web-app
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: demo-py-web-app
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: demo-py-web-app
            port: 
              number: 80
