apiVersion: apps/v1
kind: Deployment
metadata:
  name: app3
  labels:
    app: app3
  namespace: namespace-workflow-1684874448692
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app3
  template:
    metadata:
      labels:
        app: app3
    spec:
      containers:
        - name: app3
          image: akstestcr011.azurecr.io/image-workflow-1684874448692:latest
          ports:
            - containerPort: 8000