apiVersion: v1
kind: Service
metadata:
  name: app3
  namespace: namespace-workflow-1684874448692
spec:
  type: LoadBalancer
  selector:
    app: app3
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000